#!/usr/bin/env php
<?php
require __DIR__ . '/vendor/autoload.php';

use App\Framework\Console\Commands\ServeCommand;
use Symfony\Component\Console\Application;

$application = new Application();
$application->add(new ServeCommand());

$application->run();